### ISSUE TITLE
ncpu doesn't seem to work

### ISSUE THREAD

**Issue by lingminhao** [Genentech/Isosceles#3]
Hello, I tried to run scrna analysis using your tool by trying the multiprocessing functionality, i.e. adjusting the `ncpu` parameter. However, when I check my run using the top command, it was capped at 100% cpu usage. What could be the potential problem?

**Comment by brandon-hastings** [comment]
Can this be reopened? I'm experiencing the same issue. I assign 4 cpu cores on an HPC managed via slurm scheduler and only have up to 99% CPU usage via the top command for the each process that takes an `ncpu` argument. i.e. `bam_to_read_structures`, `bam_to_tcc`. This is an issue with a single cell analysis as the job times out on only one cpu.
Here is the top command of the specified process:
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                 
 168946 bthasti+  20   0 7980600   6.9g   5912 R  99.0   0.9   8:06.62 R

**Comment by brandon-hastings** [comment]
@timbitz @mkabza pinging as the issue was closed by the original poster
